lidar_topic: /velodyne_points
imu_topic: /imu/data
lidar_type: velodyne # livox velodyne ouster
min_radius: 1.0
max_radius: 150.0
point_filter_num: 6
time_scale: 1000.0 # nclt: 0.001 other: 1000.0
enable_ahrs_initalization: false
enable_acc_correct: false

scan_resolution: 0.5
voxel_map_resolution: 0.5
max_iterations: 10

acc_cov: 0.01
gyr_cov: 0.0001
ba_cov: 0.000001
bg_cov: 0.000001

gicp_constraints_gain: 100.0
point2plane_constraints_gain: 1000.0
enable_undistort: true
enable_outlier_rejection: true

gravity: 9.80665
init_ori_cov: 0.0001
inti_pos_cov: 0.0001
init_vel_cov: 100.0
init_ba_cov: 0.0001
init_bg_cov: 0.0001

# botanic graden
t_imu_lidar : [0.0584867781527745, 0.00840419966766332,0.168915521980526]
R_imu_lidar: [0.999678872580465, 0.0252865664429322, 0.00150422292234868,
              -0.0252723438960774, 0.999649431893338, -0.0078025434141585,
              -0.00170103929405540, 0.00776298237926191, 0.99996789371916]